### ISSUE TITLE
Use Django relationships backward where possible

### ISSUE THREAD

**Issue by pmckee11** [MIT-Tab/mit-tab#1]
Looks like you guys didn't know that when you create a relationship property on one model, you can access it backwards from the referenced model. This caused you to write some pretty slow code in a few places. Check how I changed the function to get a debater's team in tab_logic.py. Now viewing the ranked speakers page is almost twice as fast.

There are a bunch of other places where analogous changes can be made.

**Comment by BenMusch** [comment]
Addressed in https://github.com/MIT-Tab/mit-tab/pull/172
