### ISSUE TITLE
Make it easier to see checked-in teams

### ISSUE THREAD

**Issue by yashaslokesh** [MIT-Tab/mit-tab#244]
**Feature Request**

Templating Cleanup

The route at `/pairings/status` shows a long list of teams that aren't checked in or don't have a bye. I think the interface here could be improved to show a more-condensed view of the teams, so that all the teams that aren't checked in can be seen on one screen.

I have experience with Flask & Jinja2, I could learn Django and update the relevant template.

**Comment by BenMusch** [comment]
Thanks for reporting this!

Out of curiosity, are you familiar with the filers available on the team list view? There's a checkbox that allows you to filter by check-in. I think that may serve this purpose pretty well

**Comment by yashaslokesh** [comment]
I do know about those filters, and they are useful. Specifically on `/pairings/status`, I think there could be a better way to tell Tab about the non-checked in teams, though.

**Comment by yashaslokesh** [comment]
Additionally, we had a problem this past weekend with fake debaters, ones that were not part of any team but were still on the debaters list (input errors). We clicked on each debater and checked if they were part of a team and removed the 'fake' debaters. 

Maybe a notice could be added on the `pairings/status` page or on the `/view_debaters` page indicating all team-less debaters?

**Comment by BenMusch** [comment]
Sounds good. Does this seem like a reasonable description for how the fix should be implemented?

```
On the pairing status page, rather than having one error for each un-paired-in team, there would be one alert total, which can be expanded/collapsed to show/hide the list of all missing teams
```
