### ISSUE TITLE
Add mysqldump backup method

### ISSUE THREAD

**Issue by BenMusch** [MIT-Tab/mit-tab#282]
better than djangos dump/load

**Comment by roddajohn** [comment]
I have a way that works on another project that just excludes content types, etc that seems to work decently well

**Comment by BenMusch** [comment]
Right now it does exclude that stuff, the issue is doing a worst-case-scenario restore where we lose the content-types, and then can't load the data at all because of foreign key issues (which still happens even if you have `natural_foreign` set)

Maybe they're another way to get around this though? Does running migrations again work?
