### ISSUE TITLE
Add team/school login

### ISSUE THREAD

**Issue by andrewmin** [MIT-Tab/mit-tab#38]
This would be a really big update, but I think there are a lot of potential features that could make tournaments run more smoothly if you could let 1. individual debaters and/or 2. a school representative log into MIT-TAB. A few examples:
1. they could submit team/individual scratches automatically, without confirming with the tab staff. Scratches take a long time to deal with, and the problem with doing scratches ahead of time via a Google Doc is that judges will often change. This also mitigates the awkward issue of scratching the guy taking scratches -- they'll still be able to know, but you won't be explicitly telling them. Obviously tab scratches would still be justified to tab.
2. they can confirm information: teams/judges checked in, scratches confirmed, etc. Checkins would be especially useful: obviously, you wouldn't let them check in themselves, but they could check their status. This would be useful insofar as they'd be able to make sure they're not going to be accidentally left out of pairings, which means that pairings are less likely to be wrong. You could also add a housing field in MIT-TAB (including host's name, their phone number, their dorm address, etc.) and the teams could check who is hosting them.
3. in future iterations, you could let them do payment through MIT-TAB via PayPal or something.

**Comment by BenMusch** [comment]
Closing due to complexity -- if this gets picked up again I'll break this down into some smaller, more actionable issues
