### ISSUE TITLE
Pairing should not fail due to lack of judges

### ISSUE THREAD

**Issue by jolynch** [MIT-Tab/mit-tab#41]
[Sat Sep 20 13:09:55 2014] [error] Copied /var/www/tab/mittab/pairing_db.sqlite3 to /var/www/tab/mittab/backups/round_4_before_pairing.db
[Sat Sep 20 13:09:55 2014] [error] Traceback (most recent call last):
[Sat Sep 20 13:09:55 2014] [error]   File "/var/www/tab/mittab/apps/tab/pairing_views.py", line 100, in pair_round
[Sat Sep 20 13:09:55 2014] [error]     tab_logic.pair_round()
[Sat Sep 20 13:09:55 2014] [error]   File "/var/www/tab/mittab/libs/tab_logic.py", line 40, in pair_round
[Sat Sep 20 13:09:55 2014] [error]     validate_round_data(current_round)
[Sat Sep 20 13:09:55 2014] [error]   File "/var/www/tab/mittab/libs/tab_logic.py", line 283, in validate_round_data
[Sat Sep 20 13:09:55 2014] [error]     raise errors.NotEnoughJudgesError()

This is no good, we should not be checking that we have enough judges during pairing but rather during judge assignment.

**Comment by ifly6** [comment]
Would this not be solved simply by removing the line [here](https://github.com/jolynch/mit-tab/blob/master/mittab/libs/tab_logic.py#L291)? It's the only thing in the codebase which throws that error.
